os: linux
dist: xenial
language: python
cache: pip

python:
  - "2.7"
  - "3.7"

script:
  - pyb

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - python-codacy-coverage -r ./target/reports/scenery_coverage.xml
